// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4aIdF1HdXBxDypMrzvey1sSI0M4idlcA',
    appId: '1:201761994781:web:53eb11bffdc438a45eaef4',
    messagingSenderId: '201761994781',
    projectId: 'dalel-3a831',
    authDomain: 'dalel-3a831.firebaseapp.com',
    storageBucket: 'dalel-3a831.appspot.com',
    measurementId: 'G-TF0FPDCSKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7OFROtYZIMAIRFb9By022U_6NkH3e1xI',
    appId: '1:201761994781:android:30ba468c9b5839a95eaef4',
    messagingSenderId: '201761994781',
    projectId: 'dalel-3a831',
    storageBucket: 'dalel-3a831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eLVHucOqH_QEMmKy8HRc2vNbkxPKH_8',
    appId: '1:201761994781:ios:cf0f5266bce58fa05eaef4',
    messagingSenderId: '201761994781',
    projectId: 'dalel-3a831',
    storageBucket: 'dalel-3a831.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7eLVHucOqH_QEMmKy8HRc2vNbkxPKH_8',
    appId: '1:201761994781:ios:cf0f5266bce58fa05eaef4',
    messagingSenderId: '201761994781',
    projectId: 'dalel-3a831',
    storageBucket: 'dalel-3a831.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4aIdF1HdXBxDypMrzvey1sSI0M4idlcA',
    appId: '1:201761994781:web:29a858ba6527ffd55eaef4',
    messagingSenderId: '201761994781',
    projectId: 'dalel-3a831',
    authDomain: 'dalel-3a831.firebaseapp.com',
    storageBucket: 'dalel-3a831.appspot.com',
    measurementId: 'G-LS83RWVM2Y',
  );
}
